/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiSelfProject;

import static java.lang.Compiler.disable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import selfproject.Admin;

/**
 *
 * @author Allewaa
 */
public class Regester extends javax.swing.JFrame {

    String s;
    
    public Regester() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Admin1 = new javax.swing.JRadioButton();
        Employee1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        show = new javax.swing.JButton();
        disable = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UserName");
        jLabel1.setMaximumSize(new java.awt.Dimension(94, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(94, 22));
        jLabel1.setPreferredSize(new java.awt.Dimension(94, 22));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 130, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jLabel2.setMaximumSize(new java.awt.Dimension(87, 22));
        jLabel2.setMinimumSize(new java.awt.Dimension(87, 22));
        jLabel2.setPreferredSize(new java.awt.Dimension(87, 22));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 30));

        userName.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 220, 30));

        Password.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("choose");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 90, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign in");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 80, 30));

        buttonGroup1.add(Admin1);
        Admin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Admin1.setForeground(new java.awt.Color(255, 255, 255));
        Admin1.setText("Admin");
        Admin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admin1MouseClicked(evt);
            }
        });
        Admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin1ActionPerformed(evt);
            }
        });
        getContentPane().add(Admin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 80, -1));

        buttonGroup1.add(Employee1);
        Employee1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Employee1.setForeground(new java.awt.Color(255, 255, 255));
        Employee1.setText("Employee");
        Employee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employee1MouseClicked(evt);
            }
        });
        Employee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee1ActionPerformed(evt);
            }
        });
        getContentPane().add(Employee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        show.setBackground(new java.awt.Color(102, 102, 102));
        show.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("show");
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 60, 30));

        disable.setBackground(new java.awt.Color(102, 102, 102));
        disable.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        disable.setForeground(new java.awt.Color(255, 255, 255));
        disable.setText("show");
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        disable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableActionPerformed(evt);
            }
        });
        getContentPane().add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 60, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\New folder\\SelfProject\\src\\img\\-.jpg")); // NOI18N
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Employee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        G_Admin g=new G_Admin();
        g.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void Admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin1ActionPerformed

    private void Admin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin1MouseClicked
        // TODO add your handling code here:
        
       Admin1.setText("Admin");
       s=Admin1.getText();
       System.out.println(s);
    }//GEN-LAST:event_Admin1MouseClicked

    private void Employee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee1MouseClicked
        // TODO add your handling code here:
        
        Employee1.setText("Employee");
        s=Employee1.getText();
        System.out.println(s);
    }//GEN-LAST:event_Employee1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       Connection con=Admin.connect();
        if(con==null)
        {
         JOptionPane.showMessageDialog(this, "Connection Faild");   
        }else {
            if(null==s){
            JOptionPane.showMessageDialog(this, "INSERT USER OR ADMIN FOR LOGIN");
        }else switch(s){
            case "Admin":
        
             try {
                    String log1 = "INSERT INTO AdminAcount values (?,?)";
                    PreparedStatement pstmt=con.prepareStatement(log1);
                    pstmt.setString(1, userName.getText());
                    pstmt.setString(2, Password.getText());
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(this," INSERTION SUCCESSFUL");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(G_Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
        
                break;
                case "Employee":
        
             try {
                    String log2 = "INSERT INTO EmployeeAccount values (?,?)";
                    PreparedStatement pstmt=con.prepareStatement(log2);
                    pstmt.setString(1, userName.getText());
                    pstmt.setString(2, Password.getText());
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null," INSERTION SUCCESSFUL");
                        
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null,ex);
                }
        
                break;
                default:
                break;
        }
        }
                
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        // TODO add your handling code here:
        disable.setVisible(true);
        disable.setEnabled(true);
        Password.setEchoChar((char)0);
        show.setVisible(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        // TODO add your handling code here:
        show.setVisible(true);
        show.setEnabled(true);
        Password.setEchoChar((char)42);
        disable.setVisible(true);
        disable.setEnabled(false);
    }//GEN-LAST:event_disableMouseClicked

    private void disableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admin1;
    private javax.swing.JRadioButton Employee1;
    private javax.swing.JPasswordField Password;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton disable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton show;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
