/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiSelfProject.Panals;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import selfproject.Admin;

/**
 *
 * @author Allewaa
 */
public class ReportMeals extends javax.swing.JPanel {

    /**
     * Creates new form ReportMeals
     */
    public ReportMeals() {
        initComponents();
    }
    
     public void List(){
        DefaultTableModel table=new DefaultTableModel();
        table.addColumn("Code");
        table.addColumn("Meal");
        table.addColumn("Price");
        
        try {
        Connection con=Admin.connect();
        String sql="select * from Mealsss";
        Statement s=con.createStatement();
        ResultSet r=s.executeQuery(sql);
        while(r.next()){
            table.addRow(new Object[]{
            r.getString(1),
            r.getString(2),
            r.getString(3),
              });
        }
        TableMeal.setModel(table);
        } catch (SQLException ex) {
            Logger.getLogger(ReportEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        TableMeal = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new java.awt.GridBagLayout());

        TableMeal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Meal", "Price"
            }
        ));
        TableMeal.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                TableMealHierarchyChanged(evt);
            }
        });
        jScrollPane1.setViewportView(TableMeal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 332;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 11, 45);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void TableMealHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_TableMealHierarchyChanged
        // TODO add your handling code here:
        List();
    }//GEN-LAST:event_TableMealHierarchyChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMeal;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
