/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiSelfProject.Panals;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import selfproject.Admin;

/**
 *
 * @author Allewaa
 */
public class ResiveEmployee extends javax.swing.JPanel {

    /**
     * Creates new form ResiveEmployee
     */
    public ResiveEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        SSN = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Permanence = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(530, 370));
        setPreferredSize(new java.awt.Dimension(527, 335));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 146, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 49, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Age");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 66, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Phone");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 53, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("SSN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 34, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Salary");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 53, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Permanence");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 94, -1));

        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, -1));
        jPanel1.add(SSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, -1));
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, -1));
        jPanel1.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, -1));
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 170, -1));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, -1));

        Permanence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermanenceActionPerformed(evt);
            }
        });
        jPanel1.add(Permanence, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 170, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ubdate");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter SSN");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 320, 310));

        jLabel8.setIcon(new javax.swing.ImageIcon("F:\\ff.jpg")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 530, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void PermanenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermanenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermanenceActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Connection con=Admin.connect();
        if(null==con){
            JOptionPane.showMessageDialog(this, "Connection Faild"); 
        }else{
            
            //String Ssn=Search.getText();
             
            String sql="SELECT  * FROM Employee where ssn=?";
            try {
            PreparedStatement s =con.prepareStatement(sql);
            s.setString(1, Search.getText());
            ResultSet rs=s.executeQuery();
            if (rs.next()){
               Name.setText(rs.getString("name"));
               Age.setText(rs.getString("age"));
               Address.setText(rs.getString("address"));
               Phone.setText(rs.getString("phone"));
               SSN.setText(rs.getString("ssn"));
               Salary.setText(rs.getString("salary"));
               Permanence.setText(rs.getString("permanence"));
            }else{
                JOptionPane.showMessageDialog(null, "Sorry ! No date Found For This Id","SSN",JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(null, "Enter a Valid SSN ","SSN Information",JOptionPane.INFORMATION_MESSAGE);
                Search.setText("");
            }}catch (SQLException ex) {
                Logger.getLogger(ResiveEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Connection con=Admin.connect();
        if(null==con){
            JOptionPane.showMessageDialog(this, "Connection Faild");
        }else{
            String sql="update Employee set name='"+Name.getText()+"', age='"+ Age.getText()+"', address='"+Address.getText()+"', phone='"+Phone.getText()+"', ssn='"+ SSN.getText()+"', salary='"+Salary.getText()+"', permanence='"+Permanence.getText()+"' where ssn=?";
            try {
                PreparedStatement pr=con.prepareStatement(sql);
                pr.setString(1, Search.getText());
                pr.executeUpdate();
                JOptionPane.showMessageDialog(null, "Update Successfuly");
            } catch (SQLException ex) {
                Logger.getLogger(ResiveEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Connection con=Admin.connect();
        if(null==con){
            JOptionPane.showMessageDialog(this, "Connection Faild");
        }else{
            String sql="delete from Employee Where ssn=?";
            try {
                PreparedStatement pr=con.prepareStatement(sql);
                pr.setString(1, Search.getText());
                pr.executeUpdate();
                JOptionPane.showMessageDialog(null, "Deleted Successfuly");
            } catch (SQLException ex) {
                Logger.getLogger(ResiveEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Permanence;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField SSN;
    private javax.swing.JTextField Salary;
    private javax.swing.JTextField Search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
