/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiSelfProject.Panals;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import selfproject.Admin;

/**
 *
 * @author Allewaa
 */
public class RevierseMeals extends javax.swing.JPanel {

    /**
     * Creates new form RevierseMeals
     */
    public RevierseMeals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Meal = new javax.swing.JTextField();
        Code = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 86, -1));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 128, 24));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Meal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Code");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Priece");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        Meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealActionPerformed(evt);
            }
        });
        jPanel1.add(Meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, -1));
        jPanel1.add(Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 180, -1));
        jPanel1.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 180, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 310, 320));

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\nun.jpg")); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -50, 760, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void MealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MealActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Connection con=Admin.connect();
        if(null==con){
            JOptionPane.showMessageDialog(this, "Connection Faild"); 
        }else{
            String aql="Select * from Mealsss where code =?";
            try {
                PreparedStatement pr=con.prepareStatement(aql);
                pr.setString(1,txtSearch.getText());
                ResultSet r=pr.executeQuery();
                if(r.next()){
                 Meal.setText(r.getString("name"));
                 Code.setText(r.getString("code"));
                 Price.setText(r.getString("priece"));
                }else{
                JOptionPane.showMessageDialog(null, "Sorry ! No date Found For This Id","SSN",JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(null, "Enter a Valid SSN ","SSN Information",JOptionPane.INFORMATION_MESSAGE);
                txtSearch.setText("");
            } }catch (SQLException ex) {
                Logger.getLogger(RevierseMeals.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                    
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Connection con=Admin.connect();
        if(null==con){
            JOptionPane.showMessageDialog(this, "Connection Faild"); 
        }else{
            String sql="update Mealsss set code='"+Code.getText()+"',name='"+Meal.getText()+"',priece='"+Price.getText()+"' WHERE code=? ";
            try {
                PreparedStatement pr=con.prepareStatement(sql);
                pr.setString(1, txtSearch.getText());
                pr.executeUpdate();
                JOptionPane.showMessageDialog(null, "Update Successfuly");
            } catch (SQLException ex) {
                Logger.getLogger(RevierseMeals.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Connection con=Admin.connect();
        if(null==con){
            JOptionPane.showMessageDialog(this, "Connection Faild");
        }else{
            String sql="delete from Mealsss where code =?";
            try {
                PreparedStatement pr=con.prepareStatement(sql);
                pr.setString(1, txtSearch.getText());
                pr.executeUpdate();
                JOptionPane.showMessageDialog(null, "Deleted Successfuly");
            } catch (SQLException ex) {
                Logger.getLogger(RevierseMeals.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Code;
    private javax.swing.JTextField Meal;
    private javax.swing.JTextField Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
